export type ComponentClsType = {
  wrapperCls: string;
  wrapperInitializedCls: string;
  placeholderCls: string;
  componentCls: string;
  componentSMCls: string;
  componentMDCls: string;
  contentCls: string;
  borderedCls: string;
  virtualCls: string;
  stripeCls: string;
  noDataCls: string;
  hasFixColumnsCls: string;
  hasFixStartColumnsCls: string;
  hasFixEndColumnsCls: string;
  fixColumnsGappedCls: string;
  pingStartCls: string;
  pingEndCls: string;
  hasSummaryCls: string;
  hasXScrollbarCls: string;
  hasYScrollbarCls: string;
  hasStickyCls: string;
  rowSortingCls: string;
  headCls: string;
  headStickyCls: string;
  headInnerCls: string;
  headRowCls: string;
  filterRowCls: string;
  bodyCls: string;
  bodyInnerCls: string;
  bodyRowCls: string;
  bodyGridRowCls: string;
  bodyFixedHeightRowCls: string;
  bodyVirtualFillerCls: string;
  bodyVirtualInnerCls: string;
  bodyVirtualRowSpanCls: string;
  bodyVirtualRowSpanTopCls: string;
  bodyVirtualPreservedCls: string;
  bodyExpandableRowCls: string;
  bodySortDraggingRowCls: string;
  bodySortDraggingOverlayRowCls: string;
  bodySortFirstRowCls: string;
  bodySortLastRowCls: string;
  cellCls: string;
  filterCellCls: string;
  ellipsisCellCls: string;
  ellipsisCellInnerCls: string;
  expandControlCellCls: string;
  expandControlCls: string;
  rowSortCellCls: string;
  rowSortOverCellCls: string;
  rowSortControlCls: string;
  rowSortHandleCls: string;
  rowSortHandleDisabledCls: string;
  rowSortHandleDraggingCls: string;
  selectionCellCls: string;
  selectionControlCls: string;
  selectionControlInputCls: string;
  selectionControlContentCls: string;
  selectionCheckboxCls: string;
  selectionRadioCls: string;
  selectionControlCheckedCls: string;
  selectionControlIndeterminateCls: string;
  selectionControlDisabledCls: string;
  expandIconCls: string;
  expandIconExpandedCls: string;
  expandIconSpacedCls: string;
  expandTreeCellInnerCls: string;
  expandedRowCls: string;
  expandedRowCellCls: string;
  expandedRowContentCls: string;
  headLastCellCls: string;
  headCellResizeHandleCls: string;
  headResizableCellDisabledCls: string;
  headSortableCellCls: string;
  headSortableCellDisabledCls: string;
  headDraggingOverlayCellCls: string;
  columnSortableActiveCellCls: string;
  columnSortableHotCellCls: string;
  fixedStartCellCls: string;
  fixedStartLastCellCls: string;
  fixedStartShadowActiveCellCls: string;
  fixedEndCellCls: string;
  fixedEndFirstCellCls: string;
  fixedEndShadowActiveCellCls: string;
  noDataCellCls: string;
  noDataCellContentCls: string;
  summaryCls: string;
  summaryStickyCls: string;
  summaryInnerCls: string;
  summaryRowCls: string;
};

export type ScrollbarClsType = {
  xScrollBarCls: string;
  xScrollBarStickyCls: string;
  xScrollBarThumbCls: string;
  xScrollBarShowCls: string;
  yScrollBarCls: string;
  yScrollBarThumbCls: string;
  yScrollBarShowCls: string;
};

export type CssVarType = {
  bodyFixedHeightRowCssVar: string;
  columnsWidthCssVar: string;
  columnsWidthTotalCssVar: string;
};

export const getComponentCls = (prefixCls: string): ComponentClsType => {
  return {
    wrapperCls: `${prefixCls}-wrapper`,
    wrapperInitializedCls: `${prefixCls}-wrapper-initialized`,
    placeholderCls: `${prefixCls}-placeholder`,
    componentCls: prefixCls,
    componentSMCls: `${prefixCls}-wrapper-small`,
    componentMDCls: `${prefixCls}-wrapper-middle`,
    contentCls: `${prefixCls}-content`,
    borderedCls: `${prefixCls}-bordered`,
    virtualCls: `${prefixCls}-virtual`,
    stripeCls: `${prefixCls}-stripe`,
    noDataCls: `${prefixCls}-no-data`,
    hasFixColumnsCls: `${prefixCls}-has-fix-columns`,
    hasFixStartColumnsCls: `${prefixCls}-has-fix-start-columns`,
    hasFixEndColumnsCls: `${prefixCls}-has-fix-end-columns`,
    fixColumnsGappedCls: `${prefixCls}-fix-columns-gapped`,
    pingStartCls: `${prefixCls}-ping-start`,
    pingEndCls: `${prefixCls}-ping-end`,
    hasSummaryCls: `${prefixCls}-has-summary`,
    hasXScrollbarCls: `${prefixCls}-has-horizontal-scrollbar`,
    hasYScrollbarCls: `${prefixCls}-has-vertical-scrollbar`,
    hasStickyCls: `${prefixCls}-has-sticky`,
    rowSortingCls: `${prefixCls}-row-sorting`,
    headCls: `${prefixCls}-head`,
    headStickyCls: `${prefixCls}-head-sticky`,
    headInnerCls: `${prefixCls}-head-inner`,
    headRowCls: `${prefixCls}-head-row`,
    filterRowCls: `${prefixCls}-filter-row`,
    bodyCls: `${prefixCls}-body`,
    bodyInnerCls: `${prefixCls}-body-inner`,
    bodyRowCls: `${prefixCls}-body-row`,
    bodyGridRowCls: `${prefixCls}-body-grid-row`,
    bodyFixedHeightRowCls: `${prefixCls}-body-fixed-height-row`,
    bodyVirtualFillerCls: `${prefixCls}-body-virtual-filler`,
    bodyVirtualInnerCls: `${prefixCls}-body-virtual-inner`,
    bodyVirtualRowSpanCls: `${prefixCls}-body-virtual-row-span`,
    bodyVirtualRowSpanTopCls: `${prefixCls}-body-virtual-row-span-top`,
    bodyVirtualPreservedCls: `${prefixCls}-body-virtual-preserved`,
    bodyExpandableRowCls: `${prefixCls}-body-expandable-row`,
    bodySortDraggingRowCls: `${prefixCls}-body-sort-dragging-row`,
    bodySortDraggingOverlayRowCls: `${prefixCls}-body-sort-dragging-overlay-row`,
    bodySortFirstRowCls: `${prefixCls}-body-sort-first-row`,
    bodySortLastRowCls: `${prefixCls}-body-sort-last-row`,
    cellCls: `${prefixCls}-cell`,
    filterCellCls: `${prefixCls}-filter-cell`,
    ellipsisCellCls: `${prefixCls}-ellipsis-cell`,
    ellipsisCellInnerCls: `${prefixCls}-ellipsis-cell-inner`,
    expandControlCellCls: `${prefixCls}-expand-control-cell`,
    expandControlCls: `${prefixCls}-expand-control`,
    rowSortCellCls: `${prefixCls}-row-sort-cell`,
    rowSortOverCellCls: `${prefixCls}-row-sort-over-cell`,
    rowSortControlCls: `${prefixCls}-row-sort-control`,
    rowSortHandleCls: `${prefixCls}-row-sort-handle`,
    rowSortHandleDisabledCls: `${prefixCls}-row-sort-handle-disabled`,
    rowSortHandleDraggingCls: `${prefixCls}-row-sort-handle-dragging`,
    selectionCellCls: `${prefixCls}-selection-cell`,
    selectionControlCls: `${prefixCls}-selection-control`,
    selectionControlInputCls: `${prefixCls}-selection-control-input`,
    selectionControlContentCls: `${prefixCls}-selection-control-content`,
    selectionCheckboxCls: `${prefixCls}-selection-checkbox`,
    selectionRadioCls: `${prefixCls}-selection-radio`,
    selectionControlCheckedCls: `${prefixCls}-selection-control-checked`,
    selectionControlIndeterminateCls: `${prefixCls}-selection-control-indeterminate`,
    selectionControlDisabledCls: `${prefixCls}-selection-control-disabled`,
    expandIconCls: `${prefixCls}-expand-icon`,
    expandIconExpandedCls: `${prefixCls}-expand-icon-expanded`,
    expandIconSpacedCls: `${prefixCls}-expand-icon-spaced`,
    expandTreeCellInnerCls: `${prefixCls}-expand-tree-cell-inner`,
    expandedRowCls: `${prefixCls}-expanded-row`,
    expandedRowCellCls: `${prefixCls}-expanded-row-cell`,
    expandedRowContentCls: `${prefixCls}-expanded-row-content`,
    headLastCellCls: `${prefixCls}-head-last-cell`,
    headCellResizeHandleCls: `${prefixCls}-head-cell-resize-handle`,
    headResizableCellDisabledCls: `${prefixCls}-head-resizable-cell-disabled`,
    headSortableCellCls: `${prefixCls}-head-sortable-cell`,
    headSortableCellDisabledCls: `${prefixCls}-head-sortable-cell-disabled`,
    headDraggingOverlayCellCls: `${prefixCls}-head-dragging-overlay-cell`,
    columnSortableActiveCellCls: `${prefixCls}-column-sortable-active-cell`,
    columnSortableHotCellCls: `${prefixCls}-column-sortable-hot-cell`,
    fixedStartCellCls: `${prefixCls}-fixed-start-cell`,
    fixedStartLastCellCls: `${prefixCls}-fixed-start-last-cell`,
    fixedStartShadowActiveCellCls: `${prefixCls}-fixed-start-shadow-active-cell`,
    fixedEndCellCls: `${prefixCls}-fixed-end-cell`,
    fixedEndFirstCellCls: `${prefixCls}-fixed-end-first-cell`,
    fixedEndShadowActiveCellCls: `${prefixCls}-fixed-end-shadow-active-cell`,
    noDataCellCls: `${prefixCls}-no-data-cell`,
    noDataCellContentCls: `${prefixCls}-no-data-cell-content`,
    summaryCls: `${prefixCls}-summary`,
    summaryStickyCls: `${prefixCls}-summary-sticky`,
    summaryInnerCls: `${prefixCls}-summary-inner`,
    summaryRowCls: `${prefixCls}-summary-row`,
  };
};

export const getScrollbarCls = (prefixCls: string): ScrollbarClsType => ({
  xScrollBarCls: `${prefixCls}-horizontal-scrollbar`,
  xScrollBarStickyCls: `${prefixCls}-horizontal-scrollbar-sticky`,
  xScrollBarThumbCls: `${prefixCls}-horizontal-scrollbar-thumb`,
  xScrollBarShowCls: `${prefixCls}-horizontal-scrollbar-show`,
  yScrollBarCls: `${prefixCls}-vertical-scrollbar`,
  yScrollBarThumbCls: `${prefixCls}-vertical-scrollbar-thumb`,
  yScrollBarShowCls: `${prefixCls}-vertical-scrollbar-show`,
});

export const getCssVar = (prefixCls: string): CssVarType => ({
  bodyFixedHeightRowCssVar: `--${prefixCls}-body-fixed-height-row`,
  columnsWidthCssVar: `--${prefixCls}-columns-width`,
  columnsWidthTotalCssVar: `--${prefixCls}-columns-width-total`,
});
