export type ComponentClsType = {
  wrapperCls: string;
  wrapperInitializedCls: string;
  placeholderCls: string;
  componentCls: string;
  componentSMCls: string;
  componentMDCls: string;
  contentCls: string;
  borderedCls: string;
  virtualCls: string;
  stripeCls: string;
  noDataCls: string;
  hasFixColumnsCls: string;
  hasFixStartColumnsCls: string;
  hasFixEndColumnsCls: string;
  fixColumnsGappedCls: string;
  pingStartCls: string;
  pingEndCls: string;
  hasSummaryCls: string;
  hasXScrollbarCls: string;
  hasYScrollbarCls: string;
  hasStickyCls: string;
  headCls: string;
  headStickyCls: string;
  headInnerCls: string;
  headRowCls: string;
  filterRowCls: string;
  bodyCls: string;
  bodyInnerCls: string;
  bodyRowCls: string;
  bodyGridRowCls: string;
  bodyRowFixedHeightCls: string;
  bodyVirtualFillerCls: string;
  bodyVirtualInnerCls: string;
  bodyVirtualRowSpanCls: string;
  bodyVirtualRowSpanTopCls: string;
  bodyRowExpandableCls: string;
  bodyRowSortDraggingCls: string;
  cellCls: string;
  filterCellCls: string;
  cellEllipsisCls: string;
  cellEllipsisInnerCls: string;
  expandControlCellCls: string;
  expandControlCls: string;
  rowSortCellCls: string;
  rowSortCellOverCls: string;
  rowSortControlCls: string;
  rowSortHandleCls: string;
  rowSortHandleDisabledCls: string;
  rowSortHandleDraggingCls: string;
  selectionCellCls: string;
  selectionControlCls: string;
  selectionControlInputCls: string;
  selectionControlContentCls: string;
  selectionCheckboxCls: string;
  selectionRadioCls: string;
  selectionControlCheckedCls: string;
  selectionControlIndeterminateCls: string;
  selectionControlDisabledCls: string;
  expandIconCls: string;
  expandIconExpandedCls: string;
  expandIconSpacedCls: string;
  expandTreeCellInnerCls: string;
  expandedRowCls: string;
  expandedRowCellCls: string;
  expandedRowContentCls: string;
  headLastCellCls: string;
  headCellResizeHandleCls: string;
  headResizableCellDisabledCls: string;
  headSortableCellCls: string;
  headSortableCellDisabledCls: string;
  headDraggingOverlayCellCls: string;
  cellFixedStartCls: string;
  cellFixedStartLastCls: string;
  cellFixedStartShadowActiveCls: string;
  cellFixedEndCls: string;
  cellFixedEndFirstCls: string;
  cellFixedEndShadowActiveCls: string;
  noDataCellCls: string;
  noDataCellContentCls: string;
  summaryCls: string;
  summaryStickyCls: string;
  summaryInnerCls: string;
  summaryRowCls: string;
};

export type ScrollbarClsType = {
  xScrollBarCls: string;
  xScrollBarStickyCls: string;
  xScrollBarThumbCls: string;
  xScrollBarShowCls: string;
  yScrollBarCls: string;
  yScrollBarThumbCls: string;
  yScrollBarShowCls: string;
};

export type CssVarType = {
  bodyRowFixedHeightCssVar: string;
  colsWidthCssVar: string;
  colsWidthTotalCssVar: string;
};

export const getComponentCls = (prefixCls: string): ComponentClsType => {
  return {
    wrapperCls: `${prefixCls}-wrapper`,
    wrapperInitializedCls: `${prefixCls}-wrapper-initialized`,
    placeholderCls: `${prefixCls}-placeholder`,
    componentCls: prefixCls,
    componentSMCls: `${prefixCls}-wrapper-small`,
    componentMDCls: `${prefixCls}-wrapper-middle`,
    contentCls: `${prefixCls}-content`,
    borderedCls: `${prefixCls}-bordered`,
    virtualCls: `${prefixCls}-virtual`,
    stripeCls: `${prefixCls}-stripe`,
    noDataCls: `${prefixCls}-no-data`,
    hasFixColumnsCls: `${prefixCls}-has-fix-columns`,
    hasFixStartColumnsCls: `${prefixCls}-has-fix-start-columns`,
    hasFixEndColumnsCls: `${prefixCls}-has-fix-end-columns`,
    fixColumnsGappedCls: `${prefixCls}-fix-columns-gapped`,
    pingStartCls: `${prefixCls}-ping-start`,
    pingEndCls: `${prefixCls}-ping-end`,
    hasSummaryCls: `${prefixCls}-has-summary`,
    hasXScrollbarCls: `${prefixCls}-has-horizontal-scrollbar`,
    hasYScrollbarCls: `${prefixCls}-has-vertical-scrollbar`,
    hasStickyCls: `${prefixCls}-has-sticky`,
    headCls: `${prefixCls}-head`,
    headStickyCls: `${prefixCls}-head-sticky`,
    headInnerCls: `${prefixCls}-head-inner`,
    headRowCls: `${prefixCls}-head-row`,
    filterRowCls: `${prefixCls}-filter-row`,
    bodyCls: `${prefixCls}-body`,
    bodyInnerCls: `${prefixCls}-body-inner`,
    bodyRowCls: `${prefixCls}-body-row`,
    bodyGridRowCls: `${prefixCls}-body-grid-row`,
    bodyRowFixedHeightCls: `${prefixCls}-body-row-fixed-height`,
    bodyVirtualFillerCls: `${prefixCls}-body-virtual-filler`,
    bodyVirtualInnerCls: `${prefixCls}-body-virtual-inner`,
    bodyVirtualRowSpanCls: `${prefixCls}-body-virtual-row-span`,
    bodyVirtualRowSpanTopCls: `${prefixCls}-body-virtual-row-span-top`,
    bodyRowExpandableCls: `${prefixCls}-body-row-expandable`,
    bodyRowSortDraggingCls: `${prefixCls}-body-row-sort-dragging`,
    cellCls: `${prefixCls}-cell`,
    filterCellCls: `${prefixCls}-filter-cell`,
    cellEllipsisCls: `${prefixCls}-cell-ellipsis`,
    cellEllipsisInnerCls: `${prefixCls}-cell-ellipsis-inner`,
    expandControlCellCls: `${prefixCls}-expand-control-cell`,
    expandControlCls: `${prefixCls}-expand-control`,
    rowSortCellCls: `${prefixCls}-row-sort-cell`,
    rowSortCellOverCls: `${prefixCls}-row-sort-cell-over`,
    rowSortControlCls: `${prefixCls}-row-sort-control`,
    rowSortHandleCls: `${prefixCls}-row-sort-handle`,
    rowSortHandleDisabledCls: `${prefixCls}-row-sort-handle-disabled`,
    rowSortHandleDraggingCls: `${prefixCls}-row-sort-handle-dragging`,
    selectionCellCls: `${prefixCls}-selection-cell`,
    selectionControlCls: `${prefixCls}-selection-control`,
    selectionControlInputCls: `${prefixCls}-selection-control-input`,
    selectionControlContentCls: `${prefixCls}-selection-control-content`,
    selectionCheckboxCls: `${prefixCls}-selection-checkbox`,
    selectionRadioCls: `${prefixCls}-selection-radio`,
    selectionControlCheckedCls: `${prefixCls}-selection-control-checked`,
    selectionControlIndeterminateCls: `${prefixCls}-selection-control-indeterminate`,
    selectionControlDisabledCls: `${prefixCls}-selection-control-disabled`,
    expandIconCls: `${prefixCls}-expand-icon`,
    expandIconExpandedCls: `${prefixCls}-expand-icon-expanded`,
    expandIconSpacedCls: `${prefixCls}-expand-icon-spaced`,
    expandTreeCellInnerCls: `${prefixCls}-expand-tree-cell-inner`,
    expandedRowCls: `${prefixCls}-expanded-row`,
    expandedRowCellCls: `${prefixCls}-expanded-row-cell`,
    expandedRowContentCls: `${prefixCls}-expanded-row-content`,
    headLastCellCls: `${prefixCls}-head-last-cell`,
    headCellResizeHandleCls: `${prefixCls}-head-cell-resize-handle`,
    headResizableCellDisabledCls: `${prefixCls}-head-resizable-cell-disabled`,
    headSortableCellCls: `${prefixCls}-head-sortable-cell`,
    headSortableCellDisabledCls: `${prefixCls}-head-sortable-cell-disabled`,
    headDraggingOverlayCellCls: `${prefixCls}-head-dragging-verlay-cell`,
    cellFixedStartCls: `${prefixCls}-cell-fixed-start`,
    cellFixedStartLastCls: `${prefixCls}-cell-fixed-start-last`,
    cellFixedStartShadowActiveCls: `${prefixCls}-cell-fixed-start-shadow-active`,
    cellFixedEndCls: `${prefixCls}-cell-fixed-end`,
    cellFixedEndFirstCls: `${prefixCls}-cell-fixed-end-first`,
    cellFixedEndShadowActiveCls: `${prefixCls}-cell-fixed-end-shadow-active`,
    noDataCellCls: `${prefixCls}-no-data-cell`,
    noDataCellContentCls: `${prefixCls}-no-data-cell-content`,
    summaryCls: `${prefixCls}-summary`,
    summaryStickyCls: `${prefixCls}-summary-sticky`,
    summaryInnerCls: `${prefixCls}-summary-inner`,
    summaryRowCls: `${prefixCls}-summary-row`,
  };
};

export const getScrollbarCls = (prefixCls: string): ScrollbarClsType => ({
  xScrollBarCls: `${prefixCls}-horizontal-scrollbar`,
  xScrollBarStickyCls: `${prefixCls}-horizontal-scrollbar-sticky`,
  xScrollBarThumbCls: `${prefixCls}-horizontal-scrollbar-thumb`,
  xScrollBarShowCls: `${prefixCls}-horizontal-scrollbar-show`,
  yScrollBarCls: `${prefixCls}-vertical-scrollbar`,
  yScrollBarThumbCls: `${prefixCls}-vertical-scrollbar-thumb`,
  yScrollBarShowCls: `${prefixCls}-vertical-scrollbar-show`,
});

export const getCssVar = (prefixCls: string): CssVarType => ({
  bodyRowFixedHeightCssVar: `--${prefixCls}-body-row-fixed-height`,
  colsWidthCssVar: `--${prefixCls}-cols-width`,
  colsWidthTotalCssVar: `--${prefixCls}-cols-width-total`,
});
