export type ComponentClsType = {
  wrapperCls: string;
  wrapperInitializedCls: string;
  componentCls: string;
  componentSMCls: string;
  componentMDCls: string;
  borderedCls: string;
  virtualCls: string;
  stripeCls: string;
  noDataCls: string;
  hasSummaryCls: string;
  hasXScrollbarCls: string;
  hasYScrollbarCls: string;
  hasStickyCls: string;
  previewColumnsSortingCls: string;
  rowSortingCls: string;
  hasFixColumnsCls: string;
  fixColumnsGappedCls: string;
  pingStartCls: string;
  pingEndCls: string;
  fixedStartShadowCls: string;
  fixedStartShadowActiveCls: string;
  fixedEndShadowCls: string;
  fixedEndShadowActiveCls: string;
  placeholderCls: string;
  placeholderDisabledCls: string;
  headCls: string;
  headStickyCls: string;
  headInnerCls: string;
  headRowCls: string;
  filterRowCls: string;
  bodyCls: string;
  bodyInnerCls: string;
  bodyRowCls: string;
  bodyNoDataRowCls: string;
  bodyHoverRowCls: string;
  bodyHoverCellCls: string;
  bodyStripeRowCls: string;
  bodyVirtualFillerCls: string;
  bodyVirtualInnerCls: string;
  bodyGridRowCls: string;
  bodyFixedHeightRowCls: string;
  bodyVirtualRowSpanRowCls: string;
  bodyVirtualRowSpanTopRowCls: string;
  bodyVirtualPreservedRowCls: string;
  bodyVirtualRowSpanPlaceholderCellCls: string;
  bodyExpandableRowCls: string;
  bodyExpandedRowCls: string;
  bodyExpandedRowCellCls: string;
  bodyExpandedRowContentCls: string;
  bodySortDraggingRowCls: string;
  bodySortDraggingOverlayRowCls: string;
  bodySortFirstRowCls: string;
  bodySortLastRowCls: string;
  cellCls: string;
  filterCellCls: string;
  ellipsisCellCls: string;
  ellipsisCellInnerCls: string;
  dataSortCellCls: string;
  dataSortActiveCellCls: string;
  dataSortCellInnerCls: string;
  dataSortContentCls: string;
  dataSortControlCls: string;
  rowSortCellCls: string;
  rowSortOverCellCls: string;
  rowSortHandleCls: string;
  rowSortHandleDisabledCls: string;
  rowSortHandleDraggingCls: string;
  selectionCellCls: string;
  selectionControlCls: string;
  selectionControlDisabledCls: string;
  expandCellCls: string;
  expandControlCls: string;
  expandControlExpandedCls: string;
  expandTreeCellCls: string;
  expandTreeCellInnerCls: string;
  expandTreeCellInnerSpacedCls: string;
  expandTreeControlCls: string;
  expandTreeContentCls: string;
  headLastCellCls: string;
  headCellResizeHandleCls: string;
  headCellResizeHandleDisabledCls: string;
  headResizableCellDisabledCls: string;
  headSortableCellCls: string;
  headSortableCellDisabledCls: string;
  headDraggingOverlayCellCls: string;
  columnSortableActiveCellCls: string;
  columnSortableHotCellCls: string;
  previewHiddenCellCls: string;
  previewRestoredCellCls: string;
  fixedStartCellCls: string;
  fixedStartLastCellCls: string;
  fixedStartShadowActiveCellCls: string;
  fixedEndCellCls: string;
  fixedEndFirstCellCls: string;
  fixedEndShadowActiveCellCls: string;
  noDataCellCls: string;
  noDataCellContentCls: string;
  summaryCls: string;
  summaryStickyCls: string;
  summaryInnerCls: string;
  summaryRowCls: string;
};

export type ScrollbarClsType = {
  xScrollBarCls: string;
  xScrollBarStickyCls: string;
  xScrollBarThumbCls: string;
  xScrollBarShowCls: string;
  yScrollBarCls: string;
  yScrollBarThumbCls: string;
  yScrollBarShowCls: string;
};

export type CssVarType = {
  bodyFixedHeightRowCssVar: string;
  columnsWidthCssVar: string;
  columnsWidthTotalCssVar: string;
};

export const getComponentCls = (prefixCls: string): ComponentClsType => {
  return {
    wrapperCls: `${prefixCls}-wrapper`,
    wrapperInitializedCls: `${prefixCls}-wrapper-initialized`,
    componentCls: prefixCls,
    componentSMCls: `${prefixCls}-wrapper-small`,
    componentMDCls: `${prefixCls}-wrapper-middle`,
    borderedCls: `${prefixCls}-bordered`,
    virtualCls: `${prefixCls}-virtual`,
    stripeCls: `${prefixCls}-stripe`,
    noDataCls: `${prefixCls}-no-data`,
    hasSummaryCls: `${prefixCls}-has-summary`,
    hasXScrollbarCls: `${prefixCls}-has-horizontal-scrollbar`,
    hasYScrollbarCls: `${prefixCls}-has-vertical-scrollbar`,
    hasStickyCls: `${prefixCls}-has-sticky`,
    previewColumnsSortingCls: `${prefixCls}-preview-columns-sorting`,
    rowSortingCls: `${prefixCls}-row-sorting`,
    hasFixColumnsCls: `${prefixCls}-has-fix-columns`,
    fixColumnsGappedCls: `${prefixCls}-fix-columns-gapped`,
    pingStartCls: `${prefixCls}-ping-start`,
    pingEndCls: `${prefixCls}-ping-end`,
    fixedStartShadowCls: `${prefixCls}-fixed-start-shadow`,
    fixedStartShadowActiveCls: `${prefixCls}-fixed-start-shadow-active`,
    fixedEndShadowCls: `${prefixCls}-fixed-end-shadow`,
    fixedEndShadowActiveCls: `${prefixCls}-fixed-end-shadow-active`,
    placeholderCls: `${prefixCls}-placeholder`,
    placeholderDisabledCls: `${prefixCls}-placeholder-disabled`,
    headCls: `${prefixCls}-head`,
    headStickyCls: `${prefixCls}-head-sticky`,
    headInnerCls: `${prefixCls}-head-inner`,
    headRowCls: `${prefixCls}-head-row`,
    filterRowCls: `${prefixCls}-filter-row`,
    bodyCls: `${prefixCls}-body`,
    bodyInnerCls: `${prefixCls}-body-inner`,
    bodyRowCls: `${prefixCls}-body-row`,
    bodyNoDataRowCls: `${prefixCls}-body-no-data-row`,
    bodyHoverRowCls: `${prefixCls}-body-hover-row`,
    bodyHoverCellCls: `${prefixCls}-body-hover-cell`,
    bodyStripeRowCls: `${prefixCls}-body-stripe-row`,
    bodyVirtualFillerCls: `${prefixCls}-body-virtual-filler`,
    bodyVirtualInnerCls: `${prefixCls}-body-virtual-inner`,
    bodyGridRowCls: `${prefixCls}-body-grid-row`,
    bodyFixedHeightRowCls: `${prefixCls}-body-fixed-height-row`,
    bodyVirtualRowSpanRowCls: `${prefixCls}-body-virtual-row-span-row`,
    bodyVirtualRowSpanTopRowCls: `${prefixCls}-body-virtual-row-span-top-row`,
    bodyVirtualPreservedRowCls: `${prefixCls}-body-virtual-preserved-row`,
    bodyVirtualRowSpanPlaceholderCellCls: `${prefixCls}-body-virtual-row-span-placeholder-cell`,
    bodyExpandableRowCls: `${prefixCls}-body-expandable-row`,
    bodyExpandedRowCls: `${prefixCls}-body-expanded-row`,
    bodyExpandedRowCellCls: `${prefixCls}-body-expanded-row-cell`,
    bodyExpandedRowContentCls: `${prefixCls}-body-expanded-row-content`,
    bodySortDraggingRowCls: `${prefixCls}-body-sort-dragging-row`,
    bodySortDraggingOverlayRowCls: `${prefixCls}-body-sort-dragging-overlay-row`,
    bodySortFirstRowCls: `${prefixCls}-body-sort-first-row`,
    bodySortLastRowCls: `${prefixCls}-body-sort-last-row`,
    cellCls: `${prefixCls}-cell`,
    filterCellCls: `${prefixCls}-filter-cell`,
    ellipsisCellCls: `${prefixCls}-ellipsis-cell`,
    ellipsisCellInnerCls: `${prefixCls}-ellipsis-cell-inner`,
    dataSortCellCls: `${prefixCls}-data-sort-cell`,
    dataSortActiveCellCls: `${prefixCls}-data-sort-active-cell`,
    dataSortCellInnerCls: `${prefixCls}-data-sort-cell-inner`,
    dataSortContentCls: `${prefixCls}-data-sort-content`,
    dataSortControlCls: `${prefixCls}-data-sort-control`,
    expandCellCls: `${prefixCls}-expand-cell`,
    rowSortCellCls: `${prefixCls}-row-sort-cell`,
    rowSortOverCellCls: `${prefixCls}-row-sort-over-cell`,
    rowSortHandleCls: `${prefixCls}-row-sort-handle`,
    rowSortHandleDisabledCls: `${prefixCls}-row-sort-handle-disabled`,
    rowSortHandleDraggingCls: `${prefixCls}-row-sort-handle-dragging`,
    selectionCellCls: `${prefixCls}-selection-cell`,
    selectionControlCls: `${prefixCls}-selection-control`,
    selectionControlDisabledCls: `${prefixCls}-selection-control-disabled`,
    expandControlCls: `${prefixCls}-expand-control`,
    expandControlExpandedCls: `${prefixCls}-expand-control-expanded`,
    expandTreeCellCls: `${prefixCls}-expand-tree-cell`,
    expandTreeCellInnerCls: `${prefixCls}-expand-tree-cell-inner`,
    expandTreeCellInnerSpacedCls: `${prefixCls}-expand-tree-cell-inner-spaced`,
    expandTreeControlCls: `${prefixCls}-expand-tree-control`,
    expandTreeContentCls: `${prefixCls}-expand-tree-content`,
    headLastCellCls: `${prefixCls}-head-last-cell`,
    headCellResizeHandleCls: `${prefixCls}-head-cell-resize-handle`,
    headCellResizeHandleDisabledCls: `${prefixCls}-head-cell-resize-handle-disabled`,
    headResizableCellDisabledCls: `${prefixCls}-head-resizable-cell-disabled`,
    headSortableCellCls: `${prefixCls}-head-sortable-cell`,
    headSortableCellDisabledCls: `${prefixCls}-head-sortable-cell-disabled`,
    headDraggingOverlayCellCls: `${prefixCls}-head-dragging-overlay-cell`,
    columnSortableActiveCellCls: `${prefixCls}-column-sortable-active-cell`,
    columnSortableHotCellCls: `${prefixCls}-column-sortable-hot-cell`,
    previewHiddenCellCls: `${prefixCls}-preview-hidden-cell`,
    previewRestoredCellCls: `${prefixCls}-preview-restored-cell`,
    fixedStartCellCls: `${prefixCls}-fixed-start-cell`,
    fixedStartLastCellCls: `${prefixCls}-fixed-start-last-cell`,
    fixedStartShadowActiveCellCls: `${prefixCls}-fixed-start-shadow-active-cell`,
    fixedEndCellCls: `${prefixCls}-fixed-end-cell`,
    fixedEndFirstCellCls: `${prefixCls}-fixed-end-first-cell`,
    fixedEndShadowActiveCellCls: `${prefixCls}-fixed-end-shadow-active-cell`,
    noDataCellCls: `${prefixCls}-no-data-cell`,
    noDataCellContentCls: `${prefixCls}-no-data-cell-content`,
    summaryCls: `${prefixCls}-summary`,
    summaryStickyCls: `${prefixCls}-summary-sticky`,
    summaryInnerCls: `${prefixCls}-summary-inner`,
    summaryRowCls: `${prefixCls}-summary-row`,
  };
};

export const getScrollbarCls = (prefixCls: string): ScrollbarClsType => ({
  xScrollBarCls: `${prefixCls}-horizontal-scrollbar`,
  xScrollBarStickyCls: `${prefixCls}-horizontal-scrollbar-sticky`,
  xScrollBarThumbCls: `${prefixCls}-horizontal-scrollbar-thumb`,
  xScrollBarShowCls: `${prefixCls}-horizontal-scrollbar-show`,
  yScrollBarCls: `${prefixCls}-vertical-scrollbar`,
  yScrollBarThumbCls: `${prefixCls}-vertical-scrollbar-thumb`,
  yScrollBarShowCls: `${prefixCls}-vertical-scrollbar-show`,
});

export const getCssVar = (prefixCls: string): CssVarType => ({
  bodyFixedHeightRowCssVar: `--${prefixCls}-body-fixed-height-row`,
  columnsWidthCssVar: `--${prefixCls}-columns-width`,
  columnsWidthTotalCssVar: `--${prefixCls}-columns-width-total`,
});
