name: Publish to npm

# 当push v*的时候会运行这个action，如：在本地执行git push origin v1.1.0，会运行这个workflow
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
# on:
#   push:
#     branches:
#       # 触发ci/cd的代码分支
#       - main

# on:
#   release:
#     types: [published]  # 只在正式发布时触发


jobs:
  build:
    # 指定操作系统
    runs-on: ubuntu-latest
    steps:
      # 将代码拉到虚拟机
      - name: 获取源码 🛎️
        uses: actions/checkout@v4
      # 指定node版本
      - name: Node环境版本 🗜️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      # 依赖缓存策略
      - name: Npm缓存 📁
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      # 依赖下载
      - name: 安装依赖 📦
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm install
      # 打包
      - name: 打包 🏗️
        run: npm run build
      # 测试
      #- name: 测试 💣
      #  run: npm run test
      # 发布
      - name: 发布 🚀
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 打包
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -zcvf release.tgz ./es/ ./lib/ LICENSE package.json README.md
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_NPM_TOKEN }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./release.tgz
          draft: false